02 flask_learning_2/views/articles.py
from flask import Blueprint,render_template
from flask import redirect,url_for,request
import sys 
sys.path.append('..')
from models import Article,Category
from app import db
from libs import login_required

article_app = Blueprint("article_app",__name__)

@article_app.route('/list',methods=['get','post'])
def articleList():
    if request.method=='POST':
        field,name = request.form['field'],request.form['name']
        if field == 'id':
            condition = Article.id.like('%{}%'.format(name))
        else:
            condition = Article.title.like('%{}%'.format(name))
        articles = Article.query.filter(condition).all()
    else:
        articles = Article.query.all()
    return render_template('article/article_list.html',articles=articles)

@article_app.route('/view/<int:article_id>')
def view(article_id):
    article = Article.query.get(article_id)
    # 查询不到时返回文章列表
    if not article:
        return redirect(url_for('article_app.articleList'))
    return render_template('article/detail.html',article=article)

@article_app.route('/delete/<int:article_id>')
@login_required  # 设置视图函数保护
def delete(article_id):
    article = Article.query.get(article_id)
    db.session.delete(article)
    db.session.commit()
    return redirect(url_for('article_app.articleList'))

@article_app.route('/edit/<int:article_id>',methods=['get','post'])
@login_required
def edit(article_id):
    article = Article.query.get(article_id)
    if request.method == 'POST':
        article.title = request.form['title']
        # article.author = 
        article.content = request.form['content']
        article.category_id = request.form['category']
        db.session.commit()
    return render_template('article/edit.html',article=article)

@article_app.route('/post',methods=['get','post'])
@login_required
def post():
    if request.method == 'POST':
        article_title = request.form['title']
        article_content = request.form['content']
        article_category = request.form['category']
        article = Article(title=article_title,content=article_content,category_id=article_category)
        db.session.add(article)
        db.session.commit()
    return render_template('article/post.html')

##### category #####

@article_app.route('/add_category',methods=['get','post'])
@login_required
def addCategory():
    message = ''
    if request.method == "POST":
        name = request.form['name']
        order = request.form['order']
        category = Category(name=name,order=order)
        # 因为models中name字段设置了unique，存在添加失败可能
        try:
            db.session.add(category)
            db.session.commit()
            message = name + " is added successfully"
        except Exception as e:
            message = "There is some problems: "+ str(e)
            db.session.rollback()
    return render_template('category/add.html',message=message)

@article_app.route('/category')
def categoryList():

    # need a search function
    
    # 按降序排列  
    categorys = Category.query.order_by(Category.order.desc()).all()
    return render_template('/category/list.html',categorys=categorys)

@article_app.route('/delete_category/<int:id>')
@login_required
def deleteCategory(id):
    category = Category.query.get(id)
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('article_app.categoryList'))

@article_app.route('/edit_category/<int:id>',methods=['get','post'])
@login_required
def editCategory(id):
    category = Category.query.get(id)
    if request.method == "POST":
        category.name = request.form['name']
        category.order = request.form['order']
        db.session.commit()
    return render_template('category/edit.html',category=category)

@article_app.route('/category_view/<int:category_id>')
def articleListByCategory(category_id):
    res = Article.query.filter_by(category_id=category_id).all()
    return render_template('article/article_list.html',articles=res)

02 flask_learning_2/templates/article/article_list.html
{% extends "index.html" %}
{% block container %}
<strong>
    Article List
</strong>
<a href="/article/post">post</a>
<form  method="POST">
    <label for="search">search</label>
    <select name="field" id="">
        <option value="id">id</option>
        <option value="artileName">article name</option>
    </select>
    <input type="text" name="name">
    <input type="submit" value="submit">
</form>
<!-- <table>
    <tr>
        <td>
            总页数:{{ pages }} / 总记录：{{ total }}
        </td>
    </tr>
</table> -->
<table >
    <tr>
        <th>id</th><th>name</th><th>author</th><th>date</th>
    </tr>
    {% for article in articles %}
    <tr>
        <td>
            {{ article.id }}
        </td>
        <td>
            <a href="{{url_for('article_app.view',article_id=article.id)}}">{{ article.title }}</a>
        </td>
        <td>
            {{article.author}}
        </td>
        <td>
            {{article.date}}
        </td>
        <td>
            {% if username %}
            <a href="{{url_for('article_app.delete',article_id=article.id)}}">delete</a>
            <a href="{{url_for('article_app.edit',article_id=article.id)}}">edit</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
<!-- <ul type=None>
{% for page in pageList %}
    {% if page != None %}
        <li>
            <a href="?page={{ page }}">{{ page }}</a>
        </li>
    {% else %}
        <li>
            <a href="#">...</a>
        </li>
    {% endif %}
{% endfor %}
</ul> -->
{% endblock%}

02 flask_learning_2/templates/article/detail.html
{% extends "index.html" %}
{% block container %}
<div>
    <article>
        <h1>
            {{article.title}}
        </h1>
        {{article.content |safe}}
    </article>
</div>
{% endblock %}

02 flask_learning_2/templates/article/edit.html
{% extends "index.html" %}
{% block container %}
<h1>
    edit the article
</h1>
<!-- 好多次忘记将form 的 method方法改为post，使得网页发送get方法而我视图函数却接受不到 -->
<form action="" method="POST">
    <label for="title">title</label>
    <input type="text" name="title" value="{{article.title}}"><br>
    <label for="content">content</label><br>
    <textarea name="content" row="30" cols="30" >{{article.content}}</textarea><br>
    <label for="category">category</label>
    <select name="category" id="">
        {% for category in categorys %}
            <option value="{{category.id}}"
                {% if article.category_id == category.id%}
                    selected
                {% endif %}
            >{{category.name}}</option>
        {% endfor %}
    </select><br>
    <input type="submit" name="submit" value="submit">
</form>
<script type="text/JavaScript" src="{{url_for('static',filename='ckeditor/ckeditor.js')}}"></script>
<script>
    CKEDITOR.replace('content')
</script>
{% endblock %}

02 flask_learning_2/templates/article/post.html
{% extends "index.html" %}
{% block container %}
<h1>write article</h1>
<form action="" method="POST">
    <label for="title">title</label>
    <input type="text" name="title"><br>
    <label for="content">content</label><br>
    <textarea name="content" rows="30" rols="30"></textarea><br>
    <label for="category">category</label>
    <select name="category" id="">
        {% for category in categorys %}
            <option value="{{category.id}}">{{category.name}}</option>
        {% endfor %}
    </select><br>
    <input type="submit" name="submit" value="submit">
</form>
<!-- 将textarea替换为ckeditor -->
<script type="text/JavaScript" src="{{url_for('static',filename='ckeditor/ckeditor.js')}}"></script>
<script>
    CKEDITOR.replace('content',{
        filebrowserUploadUrl:'/upload/ckeditor'
    })
</script>
{% endblock %}